export const urls = {
    BASE_URL: "/",
    DASHBOARD: "/dashboard",
    CATEGORIES: "/categories",
    SUB_CATEGORIES: "sub-categories/:id",
    BRAND: "/brands",
    PRODUCTS: "/products",
    USERS: "/users",
    ROLE_AND_PERMISSION: "/role-permissions",
    CUSTOMERS: "/customers",
    SHIPPING: "/shipping",
    RECHARGE: "/wallet-offer",
    ORDERS: "/orders",
    NOTIFICATION: "/notification",
    FAQ: "/faq",
    COUPON: "/coupon",
    INFORMATION: "/information",
    BANNER: "/banner",
    LOGIN: "/login",

}