export const urls = {
    BASE_URL: "/",
    DASHBOARD: "/dashboard",
    CATEGORIES: "/categories",
    SEGMENT: "/segments",
    SUB_CATEGORIES: "sub-categories/:id",
    BRAND: "/brands",
    PRODUCTS: "/products",
    PRODUCTS_HANDLER: "handler",
    PRODUCTS_HANDLER_UPDATE: "handler/:product",
    USER_HANDLER: "handler",
    USER_HANDLER_UPDATE: "handler/:user",
    ROLE_HANDLER: "handler",
    SHIPPING_HANDLER: "handler",
    COUPON_HANDLER: "handler",
    COUPON_HANDLER_UPDATE: "handler/:coupon",
    BANNER_HANDLER: "handler",
    BANNER_HANDLER_UPDATE: "handler/:banner",
    NOTIFICATION_HANDLER: "handler",
    USERS: "/users",
    ROLE_AND_PERMISSION: "/role-permissions",
    CUSTOMERS: "/customers",
    SHIPPING: "/shipping",
    RECHARGE: "/wallet-offer",
    ORDERS: "/orders",
    NOTIFICATION: "/notification",
    FAQ: "/faq",
    COUPON: "/coupon",
    INFORMATION: "/information",
    BANNER: "/banner",
    LOGIN: "/login",

}